#!/usr/bin/env bash
# Build the single file an operator downloads.
#
# What ships is ONE self-contained vault.ps1: the dispatcher from src/vault.ps1 with the
# twelve VaultKit parts folded in where the loader used to be. The split is for whoever
# edits this; it was never something the operator needed to know about, and delivering it
# as twelve files meant `update` could leave a dispatcher from one version calling a
# module from another. One file cannot be half-applied.
#
#   ./build.sh          -> writes ./vault.ps1
#   ./build.sh --check  -> fails if ./vault.ps1 is not what a build would produce
set -euo pipefail
cd "$(dirname "$0")"

SRC=src/vault.ps1
OUT=vault.ps1
[ -f "$SRC" ] || { echo "no $SRC" >&2; exit 1; }

parts=$(sed -n 's/^\$VaultKitParts = @(\(.*\))$/\1/p' "$SRC" | tr -d "' " | tr ',' '\n')
[ -n "$parts" ] || { echo "could not read \$VaultKitParts out of $SRC" >&2; exit 1; }

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# Everything before the marker, then the parts, then everything after. The markers stay
# out of the output: a built file that still looked like the source would invite someone
# to edit it.
awk '/^# >>> VAULTKIT INLINE >>>$/{exit} {print}' "$SRC" > "$tmp"

{
  echo "# ----------------------------------------------------------------------------------"
  echo "# VaultKit, folded in at build time by build.sh. DO NOT EDIT THIS FILE."
  echo "# Edit src/vault.ps1 or VaultKit/<part>.ps1 and run ./build.sh."
  echo "# ----------------------------------------------------------------------------------"
} >> "$tmp"

for part in $parts; do
  f="VaultKit/$part.ps1"
  [ -f "$f" ] || { echo "missing $f" >&2; exit 1; }
  {
    echo ""
    echo "# ===== VaultKit/$part.ps1 ====="
    echo ""
  } >> "$tmp"
  cat "$f" >> "$tmp"
done

awk 'f{print} /^# <<< VAULTKIT INLINE <<<$/{f=1}' "$SRC" >> "$tmp"

if [ "${1:-}" = "--check" ]; then
  if [ -f "$OUT" ] && cmp -s "$tmp" "$OUT"; then
    echo "vault.ps1 is up to date with src/ and VaultKit/"
    exit 0
  fi
  echo "vault.ps1 is STALE - run ./build.sh" >&2
  exit 1
fi

mv "$tmp" "$OUT"
trap - EXIT
echo "built $OUT  ($(wc -l < "$OUT" | tr -d ' ') lines, $(echo "$parts" | wc -w | tr -d ' ') parts)"
